import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Cookie from "js-cookie";

import styles from "../styles/Home.module.css";

import { useAppDispatch } from "../redux/app/hooks";
import { updateLocation } from "../redux/reducers/userSlice";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const allowGeolocation = Cookie.get("allowGeolocation");

  useEffect(() => {
    navigator.geolocation.getCurrentPosition((position) => {
      dispatch(updateLocation(position));
    });
  }, [allowGeolocation, dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Stormcaster</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
